name: chatbot
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
dependencies:
  - python~=3.11
  - pip
  - faiss-cpu~=1.7.4  # CPU version of the FAISS library for efficient similarity search
  - sentence-transformers~=2.2.2  # For generating sentence embeddings
  - rich~=13.7.0  # Rich text and formatting in the terminal
  - pytorch
  - pytorch-cuda=11.7 # compatible with perlmutter default
  - cudatoolkit=11.7 # compatible with perlmutter default
  - huggingface_hub
  - transformers
  - accelerate
  - pip:
    - sfapi_client~=0.0.6 # Python client for NERSC SF API
# use the following to check that you have a GPU version of Pytorch:
# conda list pytorch
#
# modules used:
# module load python cudatoolkit cudnn pytorch
#
# to activate the environment:
# conda activate /global/cfs/cdirs/nstaff/chatbot/conda
#
# to update the environment:
# conda env update --prefix /global/cfs/cdirs/nstaff/chatbot/conda --file environment.yml --prune